<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp6</TargetFramework>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <UpgradeBackupLocation>
    </UpgradeBackupLocation>
    <OldToolsVersion>Current</OldToolsVersion>
    <TieredCompilation>true</TieredCompilation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <IlcInvariantGlobalization>true</IlcInvariantGlobalization>
    <RootAllApplicationAssemblies>false</RootAllApplicationAssemblies>
    <IlcGenerateCompleteTypeMetadata>false</IlcGenerateCompleteTypeMetadata>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>

    <!-- <DefineConstants>UNSAFE</DefineConstants> -->
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../resources/3d-placeholder.raw" />
  </ItemGroup>
</Project>
